### ISSUE TITLE
[RULE] Import meteor packages from the context

### ISSUE THREAD

**Issue by fermuch** [sungwoncho/mantra-lint#1]
What about adding a rule to `appContext` to check if everything in containers/composers is imported from the context if it is a Meteor package?

For example, insteand of having this component:

``` jsx
// INCORRECT: hard to test and isolate
import {Accounts} from 'meteor/accounts-base';

const Login = () => (
  <Accounts.UI>
);
```

It should be like this:

``` jsx
// CORRECT: easy to isolate and provide a stub for Accounts
const Login = ({Accounts}) => (
  <Accounts.UI>
);
```

For more discussion about this approach, see: https://github.com/kadirahq/mantra/issues/168#issuecomment-203392872

**Comment by sungwoncho** [comment]
You are right. [This section](https://kadirahq.github.io/mantra/#sec-React-as-the-UI) in the spec says:

> You can also import any library function and use them in the UI components. You can import them directly from NPM modules, but not from any Meteor packages.

But it sounds like a rule for `component` rather than `appContext`. It is because this package will be used like this:

``` js
import {lint} from 'mantra-lint'

lint(someCode, 'component');
// => [{ message: 'import of Meteor package found in a React component' }]
```

 You can edit `RULES.md` to add something like `noImportMeteorPackages`.

**Comment by fermuch** [comment]
Done. See https://github.com/mantrajs/mantra-lint/pull/2
